<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SubdlProDownload</RootNamespace>
    <AssemblyName>subdl-bulk-download</AssemblyName>
    <Version>0.1.0</Version>
  </PropertyGroup>

</Project>
